### ISSUE TITLE
Support for date objects

### ISSUE THREAD

**Issue by mrkev** [coolaj86/json2yaml#12]
Right now it just crashes with `Error: what the crap: date` (lol). Searched around a bit, and though I couldn't find any official date representation on the spec, [Symfony](http://symfony.com/legacy/doc/reference/1_4/en/02-YAML#chapter_02_sub_dates) suggests ISO-8601 strings, which is a pretty sensible recommendation and a simple one to implement given JS dates have that nice `.toISOString()` method.

Thoughts?

**Comment by coolaj86** [comment]
That seems to be pretty standard. If you implement it, I'll pull it in.

**Comment by coolaj86** [comment]
Oh how I lament this getting lost in the noise of my life and not being pulled in immediately. _tear_

**Comment by GuoChen-thlg** [comment]
No new version was released after the issue was merged
