### ISSUE TITLE
Git repository is unreachable due to HTTPS certificate common name error

### ISSUE THREAD

**Issue by Calinou** [coolaj86/json2yaml#21]
The Git repository is unreachable due to an error in the HTTPS certificate (or because the URL is outdated). Example in Firefox 62:

![Certificate error in Firefox](https://user-images.githubusercontent.com/180032/45921036-b760e380-bead-11e8-8b50-d29b191cc94f.png)

The URL <https://gitlab.daplie.com/coolaj86/json2yaml> does not cause this error to appear, but the repository seems to be private as it requires the user to sign in to view it.

**Comment by coolaj86** [comment]
I have updated the URL: https://git.coolaj86.com/coolaj86/json2yaml.js

Due to my experiences with hosting both on Github and then by mixing business and personal, I will now permanently host all that I do on my own domain (using gitea) so that I'm not subject to the whims of others any longer.
